fix git scan

diff --git a/.github/workflows/trufflehog.yml b/.github/workflows/trufflehog.yml
--- a/.github/workflows/trufflehog.yml
+++ b/.github/workflows/trufflehog.yml
@@ -38,7 +38,7 @@ jobs:
       # Scan git history for all secrets
       - name: Run TruffleHog
         run: |
-          trufflehog git file:///github/workspace --json > trufflehog_results.txt || true
+          trufflehog git file://./ --json > trufflehog_results.txt || true
 
       - name: Convert TruffleHog results to markdown
         run: |
@@ -82,7 +82,7 @@ jobs:
               body: results
             });
 
-      # Fail workflow if new secret detected 
+      # Fail workflow if new secret(s) detected
       - name: Scan Results Status
         if: steps.trufflehog.outcome == 'failure'
         run: exit 1
